import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ViewTransitions} from "next-view-transitions";
import "./globals.css";
import Link from "next/link";
import Navigation from "@/components/nav";
import Footer from "@/components/footer";
import Chatbot from "@/components/Chatbot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
        <body className="min-h-full flex flex-col">
          <header className="w-full max-w-7xl mx-auto px-6 py-6 flex items-center justify-between border-b border-gray-900">
            <Link href="/" className="text-white font-black text-xl tracking-tighter">PORTFOLIO
            </Link>
            <Navigation />
          </header>
          <div className="flex-grow">{children}</div>
       <Chatbot/>
        <footer>
          <Footer  />
          </footer>
           </body>
    </html>
</ViewTransitions>

  );
}
